### ISSUE TITLE
Merge all MS feature check arguments for 1.1.0 into one

### ISSUE THREAD

**Issue by Chrezm** [Chrezm/DRO-Client#284]
We should force that clients that join a server that either expects all new IC arguments that were added to 1.1.0 (showname, video, and visibility) in some particular order, or that none of them were added. This would help enforce a particular argument order that clients should expect to receive from the server, in particular preventing the case where a server only implements some selection of the new IC arguments, thus putting the client in an awkward spot of not being able to painlessly tell what argument is what.

**Comment by TrickyLeifa** [comment]
Resolved in #285 and upgraded to #289
