### ISSUE TITLE
".opus" files marked as not found even if present+not playing if not given extension

### ISSUE THREAD

**Issue by Chrezm** [Chrezm/DRO-Client#44]
Servers may indicate they have ".opus" tracks in their music list and send that information to clients. However, even if clients have the .opus files themselves, their music list will still mark those tracks as "not found". A similar phenomenon occurs with sfx tracks.

For both cases, the client will also fail to find an ".opus" track if given just the name.

**Comment by TrickyLeifa** [comment]
This should fix the issue.
