### ISSUE TITLE
Clock

### ISSUE THREAD

**Issue by Chrezm** [Chrezm/DRO-Client#47]
We need to figure out what to do with the clock, because right now in theory we could use the timer for it

**Comment by TrickyLeifa** [comment]
This issue would require more information because right now this wouldn't really provide any regarding the clock itself.

What exactly are the issues that the clock face?

**Comment by Chrezm** [comment]
```
Jerm7008/24/2020
@Iuvee  Do we want to disable the clock animations in favor of using the actual clocks we have?
Because right now when clock happens
It will show a missing no.
```

Basically, the clock currently ties in to a server packet CL, which indicates an hour value from 0 to 23 and based on that hour value chooses an image to draw (or Missingno if unavailable(. We want to figure out if it's best to keep that system as is or to rework the clock so that it uses AOTimer/some revamp of timer.

**Comment by Cerapter** [comment]
For reference, here are the relevant comments from the Discord chat:

> I've been thinkin' about the clock, and here is my suggestion.
> 
> I consider the clock to be more of roleplaying thing than a "keep track of real time" thing.
> We could keep the 0-23 values for it, or we could double it to 0-47, to express "half past X" times as well.
> Maybe -1, too, to express the lack of a clock.
> 
> I doubt most RPs get any more specific, even half hours may be a bit of a stretch.
> 
> When it comes to displaying the clock, we could have a setting to display the time as an image, and one to display it as text. Both could be independently toggled on or off.
> 
> When displaying it as text, theme creators could maybe have an image they could place as the base of the clock, and the label itself that shows the time.
> When displaying it with images, theme creators must supply at least 1 image, but they may supply up to as many as there would be separate values for the clock. The image that would be displayed would be the one that is the largest out of all the ones that display a time smaller than or equal to the current time.
> 
> So if a theme creator creates `clock_0`, `clock_6` and `clock_20` images for the times 0:00, 6:00 and 20:00, then the game would:
> - display `clock_0` when the time is between 0:00 and 5:00,
> - display `clock_6` when the time is between 6:00 and 19:00,
> - display `clock_20` when the time is betwee 20:00 and 23:00.

> I was thinking the following. If it cant find the current image, itll use the last one it had. Otherwise, itll shown the -1 / default one
> In DR there is a special case of clock called unknown time. It happens when the time is deliberately unknown

> I still think it should display the last image wherever possible
> So in the example if the clock ticked from 23 to 0 clock should still show 22
