### ISSUE TITLE
Activate the pre checkbox on character switch if always pre is true, and emote 0 demands pre or player selects sound effect

### ISSUE THREAD

**Issue by Chrezm** [Chrezm/DRO-Client#51]
If the "always_pre" config is true, selecting a character should check the Pre checkbox automatically, not only once the player has changed to an emote that indicates preanimation is required.

Moreover, if "always_pre" is true, the preanimation checkbox is not ticked and the player chooses a sound effect, the preanimation box should be ticked automatically. That is because for DRO to play a sound effect, a preanimation order must be included with the IC message.

**Comment by Cerapter** [comment]
The first part of this issue is fixed in https://github.com/Chrezm/DRO-Client/pull/54.
